name: test-run
on:
  workflow_dispatch: 
  
jobs:

  model-data: 
   runs-on: ubuntu-latest
   steps:
   
      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'
          
      - name: Install necessary libraries
        run: |
            pip install -r pipeline-scripts/reqs-model.txt      

      - name: Execute Script
        env:
          URI: ${{ secrets.GITHUB_TOKEN }}
        run: python pipeline-scripts/lfs_model.py
