name: LFS-pipeline
on:
  workflow_dispatch: 
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    outputs: 
      update_status: ${{  steps.clean.outputs.status  }}    
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'
    
      - name: Install necessary libraries
        run: |
            pip install -r src/reqs-update.txt

      - name: Execute Script
        env:
          URI: ${{ secrets.GITHUB_TOKEN }}
        run: python src/lfs_update.py
        id: clean
        
      - name: Commit and push if changed
        run: |-
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update LFS data: ${timestamp}" || exit 0
          git push     
                  
        
          
  clean-data: 
   needs: update-data
   if: needs.update-data.outputs.update_status == 'updated'
   runs-on: ubuntu-latest
   steps:
   
      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'
          
      - name: Install necessary libraries
        run: |
            pip install -r src/reqs-clean.txt      

      - name: Execute Script
        env:
          URI: ${{ secrets.GITHUB_TOKEN }}
        run: python src/lfs_clean.py
     
      - name: Commit and push
        run: |-
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git pull origin main
          git add -A
          timestamp=$(date -u)
          git commit -m "Clean LFS data: ${timestamp}" || exit 0
          git push 
          
     
  model-data: 
   needs: [update-data, clean-data]
   if: needs.update-data.outputs.update_status == 'updated'
   runs-on: ubuntu-latest
   steps:
   
      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'
          
      - name: Install necessary libraries
        run: |
            pip install -r src/reqs-model.txt      

      - name: Execute Script
        env:
          URI: ${{ secrets.GITHUB_TOKEN }}
        run: python src/lfs_model.py
     
      - name: Commit and push
        run: |-
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git pull origin main
          git add -A
          timestamp=$(date -u)
          git commit -m "Train new model: ${timestamp}" || exit 0
          git push   
