name: model
on:
  workflow_dispatch: 
  
jobs:

  model-data: 
   runs-on: ubuntu-latest
   steps:
   
      - name: Access the repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'
          
      - name: Install necessary libraries
        run: |
            pip install -r pipeline-scripts/reqs-model.txt      

      - name: Execute Script
        env:
          URI: ${{ secrets.GITHUB_TOKEN }}
        run: python pipeline-scripts/lfs_model.py

      - name: Commit and push
        run: |-
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git pull origin main
          git add -A
          timestamp=$(date -u)
          git commit -m "Train new model: ${timestamp}" || exit 0
          git push   
